## Operations on missing data

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5, np.nan, 7, 8, 9, 10],
    'B': [np.nan, 2, 3, 4, 5, 6, np.nan, 8, 9, 10],
    'C': [1, 2, 3, np.nan, np.nan, 6, 7, np.nan, 9, 10],
    'D': [1, np.nan, np.nan, np.nan, 5, 6, 7, 8, np.nan, 10],
    'E': [np.nan, 12, 13, 14, np.nan, 16, 17, 18, 19, 20],
    'F': [21, 22, np.nan, 24, 25, np.nan, 27, 28, 29, 30],
    'G': [31, np.nan, 33, 34, 35, 36, np.nan, 38, 39, 40],
    'H': [41, 42, 43, np.nan, 45, 46, 47, np.nan, 49, 50]
}

df = pd.DataFrame(data)
df

      A     B     C     D     E     F     G     H
0   1.0   NaN   1.0   1.0   NaN  21.0  31.0  41.0
1   2.0   2.0   2.0   NaN  12.0  22.0   NaN  42.0
2   NaN   3.0   3.0   NaN  13.0   NaN  33.0  43.0
3   4.0   4.0   NaN   NaN  14.0  24.0  34.0   NaN
4   5.0   5.0   NaN   5.0   NaN  25.0  35.0  45.0
5   NaN   6.0   6.0   6.0  16.0   NaN  36.0  46.0
6   7.0   NaN   7.0   7.0  17.0  27.0   NaN  47.0
7   8.0   8.0   NaN   8.0  18.0  28.0  38.0   NaN
8   9.0   9.0   9.0   NaN  19.0  29.0  39.0  49.0
9  10.0  10.0  10.0  10.0  20.0  30.0  40.0  50.0

Find the missing data

In [3]:
df.isna()

       A      B      C      D      E      F      G      H
0  False   True  False  False   True  False  False  False
1  False  False  False   True  False  False   True  False
2   True  False  False   True  False   True  False  False
3  False  False   True   True  False  False  False   True
4  False  False   True  False   True  False  False  False
5   True  False  False  False  False   True  False  False
6  False   True  False  False  False  False   True  False
7  False  False   True  False  False  False  False   True
8  False  False  False   True  False  False  False  False
9  False  False  False  False  False  False  False  False

In [6]:
df.isna().sum(axis=1)

0    2
1    2
2    3
3    3
4    2
5    2
6    2
7    2
8    1
9    0
dtype: int64

In [10]:
df.isna().any()

A    True
B    True
C    True
D    True
E    True
F    True
G    True
H    True
dtype: bool

Removing the missing data

In [18]:
df.dropna()

      A     B     C     D     E     F     G     H
9  10.0  10.0  10.0  10.0  20.0  30.0  40.0  50.0

In [17]:
df.dropna(thresh=6)

      A     B     C     D     E     F     G     H
0   1.0   NaN   1.0   1.0   NaN  21.0  31.0  41.0
1   2.0   2.0   2.0   NaN  12.0  22.0   NaN  42.0
4   5.0   5.0   NaN   5.0   NaN  25.0  35.0  45.0
5   NaN   6.0   6.0   6.0  16.0   NaN  36.0  46.0
6   7.0   NaN   7.0   7.0  17.0  27.0   NaN  47.0
7   8.0   8.0   NaN   8.0  18.0  28.0  38.0   NaN
8   9.0   9.0   9.0   NaN  19.0  29.0  39.0  49.0
9  10.0  10.0  10.0  10.0  20.0  30.0  40.0  50.0

Filling the missing data

In [19]:
df

      A     B     C     D     E     F     G     H
0   1.0   NaN   1.0   1.0   NaN  21.0  31.0  41.0
1   2.0   2.0   2.0   NaN  12.0  22.0   NaN  42.0
2   NaN   3.0   3.0   NaN  13.0   NaN  33.0  43.0
3   4.0   4.0   NaN   NaN  14.0  24.0  34.0   NaN
4   5.0   5.0   NaN   5.0   NaN  25.0  35.0  45.0
5   NaN   6.0   6.0   6.0  16.0   NaN  36.0  46.0
6   7.0   NaN   7.0   7.0  17.0  27.0   NaN  47.0
7   8.0   8.0   NaN   8.0  18.0  28.0  38.0   NaN
8   9.0   9.0   9.0   NaN  19.0  29.0  39.0  49.0
9  10.0  10.0  10.0  10.0  20.0  30.0  40.0  50.0

In [20]:
df.fillna(0)

      A     B     C     D     E     F     G     H
0   1.0   0.0   1.0   1.0   0.0  21.0  31.0  41.0
1   2.0   2.0   2.0   0.0  12.0  22.0   0.0  42.0
2   0.0   3.0   3.0   0.0  13.0   0.0  33.0  43.0
3   4.0   4.0   0.0   0.0  14.0  24.0  34.0   0.0
4   5.0   5.0   0.0   5.0   0.0  25.0  35.0  45.0
5   0.0   6.0   6.0   6.0  16.0   0.0  36.0  46.0
6   7.0   0.0   7.0   7.0  17.0  27.0   0.0  47.0
7   8.0   8.0   0.0   8.0  18.0  28.0  38.0   0.0
8   9.0   9.0   9.0   0.0  19.0  29.0  39.0  49.0
9  10.0  10.0  10.0  10.0  20.0  30.0  40.0  50.0

In [21]:
df.fillna({'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7})

      A     B     C     D     E     F     G     H
0   1.0   1.0   1.0   1.0   4.0  21.0  31.0  41.0
1   2.0   2.0   2.0   3.0  12.0  22.0   6.0  42.0
2   0.0   3.0   3.0   3.0  13.0   5.0  33.0  43.0
3   4.0   4.0   2.0   3.0  14.0  24.0  34.0   7.0
4   5.0   5.0   2.0   5.0   4.0  25.0  35.0  45.0
5   0.0   6.0   6.0   6.0  16.0   5.0  36.0  46.0
6   7.0   1.0   7.0   7.0  17.0  27.0   6.0  47.0
7   8.0   8.0   2.0   8.0  18.0  28.0  38.0   7.0
8   9.0   9.0   9.0   3.0  19.0  29.0  39.0  49.0
9  10.0  10.0  10.0  10.0  20.0  30.0  40.0  50.0

In [22]:
df.fillna(df.mean())

       A       B          C          D       E      F      G       H
0   1.00   5.875   1.000000   1.000000  16.125  21.00  31.00  41.000
1   2.00   2.000   2.000000   6.166667  12.000  22.00  35.75  42.000
2   5.75   3.000   3.000000   6.166667  13.000  25.75  33.00  43.000
3   4.00   4.000   5.428571   6.166667  14.000  24.00  34.00  45.375
4   5.00   5.000   5.428571   5.000000  16.125  25.00  35.00  45.000
5   5.75   6.000   6.000000   6.000000  16.000  25.75  36.00  46.000
6   7.00   5.875   7.000000   7.000000  17.000  27.00  35.75  47.000
7   8.00   8.000   5.428571   8.000000  18.000  28.00  38.00  45.375
8   9.00   9.000   9.000000   6.166667  19.000  29.00  39.00  49.000
9  10.00  10.000  10.000000  10.000000  20.000  30.00  40.00  50.000