## Data Frame

In [29]:
import numpy as np
import pandas as pd

In [30]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Isabella', 'Jack', 'Kevin', 'Lily', 'Michael', 'Nina', 'Oliver'],
    'age': [25, 30, 35, 28, 24, 40, 32, 29, 27, 31, 45, 26, 38, 33, 36],
    'city': [
        'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Columbus', 'Charlotte', 'Seattle'
    ],
    'salary': [50000, 60000, 70000, 55000, 48000, 85000, 62000, 58000, 52000, 65000, 90000, 51000, 75000, 68000, 80000]
}

In [31]:
df = pd.DataFrame(data=data)

In [32]:
df

        name  age          city  salary
0      Alice   25      New York   50000
1        Bob   30   Los Angeles   60000
2    Charlie   35       Chicago   70000
3      David   28       Houston   55000
4       Emma   24       Phoenix   48000
5      Frank   40  Philadelphia   85000
6      Grace   32   San Antonio   62000
7      Henry   29     San Diego   58000
8   Isabella   27        Dallas   52000
9       Jack   31      San Jose   65000
10     Kevin   45        Austin   90000
11      Lily   26  Jacksonville   51000
12   Michael   38      Columbus   75000
13      Nina   33     Charlotte   68000
14    Oliver   36       Seattle   80000

In [33]:
from sqlalchemy import column
from streamlit import columns


data_list = [
    ['Alice', 25, 'New York', 50000],
    ['Bob', 30, 'Los Angeles', 60000],
    ['Charlie', 35, 'Chicago', 70000],
    ['David', 28, 'Houston', 55000],
    ['Emma', 24, 'Phoenix', 48000],
    ['Frank', 40, 'Philadelphia', 85000],
    ['Grace', 32, 'San Antonio', 62000],
    ['Henry', 29, 'San Diego', 58000],
    ['Isabella', 27, 'Dallas', 52000],
    ['Jack', 31, 'San Jose', 65000],
    ['Kevin', 45, 'Austin', 90000],
    ['Lily', 26, 'Jacksonville', 51000],
    ['Michael', 38, 'Columbus', 75000],
    ['Nina', 33, 'Charlotte', 68000],
    ['Oliver', 36, 'Seattle', 80000]
]
columns = ['name', 'age', 'city', 'salary']
df = pd.DataFrame(data=data_list, columns=columns)
df

        name  age          city  salary
0      Alice   25      New York   50000
1        Bob   30   Los Angeles   60000
2    Charlie   35       Chicago   70000
3      David   28       Houston   55000
4       Emma   24       Phoenix   48000
5      Frank   40  Philadelphia   85000
6      Grace   32   San Antonio   62000
7      Henry   29     San Diego   58000
8   Isabella   27        Dallas   52000
9       Jack   31      San Jose   65000
10     Kevin   45        Austin   90000
11      Lily   26  Jacksonville   51000
12   Michael   38      Columbus   75000
13      Nina   33     Charlotte   68000
14    Oliver   36       Seattle   80000

Selection and indexing of columns

In [34]:
df[['name', 'salary']]

        name  salary
0      Alice   50000
1        Bob   60000
2    Charlie   70000
3      David   55000
4       Emma   48000
5      Frank   85000
6      Grace   62000
7      Henry   58000
8   Isabella   52000
9       Jack   65000
10     Kevin   90000
11      Lily   51000
12   Michael   75000
13      Nina   68000
14    Oliver   80000

creating a column or adding a column

In [35]:
df["designation"] = ["manager", "developer", "doctor", "developer", "architect", "developer", "manager", "doctor", "manager", "developer", "manager", "Teacher", "manager", "developer", "manager"]
df

        name  age          city  salary designation
0      Alice   25      New York   50000     manager
1        Bob   30   Los Angeles   60000   developer
2    Charlie   35       Chicago   70000      doctor
3      David   28       Houston   55000   developer
4       Emma   24       Phoenix   48000   architect
5      Frank   40  Philadelphia   85000   developer
6      Grace   32   San Antonio   62000     manager
7      Henry   29     San Diego   58000      doctor
8   Isabella   27        Dallas   52000     manager
9       Jack   31      San Jose   65000   developer
10     Kevin   45        Austin   90000     manager
11      Lily   26  Jacksonville   51000     Teacher
12   Michael   38      Columbus   75000     manager
13      Nina   33     Charlotte   68000   developer
14    Oliver   36       Seattle   80000     manager

deleting a column

In [36]:
df = df.drop("designation", axis=1)
df

        name  age          city  salary
0      Alice   25      New York   50000
1        Bob   30   Los Angeles   60000
2    Charlie   35       Chicago   70000
3      David   28       Houston   55000
4       Emma   24       Phoenix   48000
5      Frank   40  Philadelphia   85000
6      Grace   32   San Antonio   62000
7      Henry   29     San Diego   58000
8   Isabella   27        Dallas   52000
9       Jack   31      San Jose   65000
10     Kevin   45        Austin   90000
11      Lily   26  Jacksonville   51000
12   Michael   38      Columbus   75000
13      Nina   33     Charlotte   68000
14    Oliver   36       Seattle   80000

In [37]:
df.drop(0, axis=0, inplace=True)
df

        name  age          city  salary
1        Bob   30   Los Angeles   60000
2    Charlie   35       Chicago   70000
3      David   28       Houston   55000
4       Emma   24       Phoenix   48000
5      Frank   40  Philadelphia   85000
6      Grace   32   San Antonio   62000
7      Henry   29     San Diego   58000
8   Isabella   27        Dallas   52000
9       Jack   31      San Jose   65000
10     Kevin   45        Austin   90000
11      Lily   26  Jacksonville   51000
12   Michael   38      Columbus   75000
13      Nina   33     Charlotte   68000
14    Oliver   36       Seattle   80000

location

In [41]:
df

        name  age          city  salary
1        Bob   30   Los Angeles   60000
2    Charlie   35       Chicago   70000
3      David   28       Houston   55000
4       Emma   24       Phoenix   48000
5      Frank   40  Philadelphia   85000
6      Grace   32   San Antonio   62000
7      Henry   29     San Diego   58000
8   Isabella   27        Dallas   52000
9       Jack   31      San Jose   65000
10     Kevin   45        Austin   90000
11      Lily   26  Jacksonville   51000
12   Michael   38      Columbus   75000
13      Nina   33     Charlotte   68000
14    Oliver   36       Seattle   80000

In [42]:
df.loc[[1,2]]

      name  age         city  salary
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [43]:
df.iloc[[1,2]]

      name  age     city  salary
2  Charlie   35  Chicago   70000
3    David   28  Houston   55000

In [44]:
df.loc[[1,2], ["name", "age"]]

      name  age
1      Bob   30
2  Charlie   35

In [46]:
df.loc[[4,5], ["name","age"]]

    name  age
4   Emma   24
5  Frank   40

Only selects people whose age is more than 30

In [56]:
df[df['age'] >= 30]

       name  age          city  salary
1       Bob   30   Los Angeles   60000
2   Charlie   35       Chicago   70000
5     Frank   40  Philadelphia   85000
6     Grace   32   San Antonio   62000
9      Jack   31      San Jose   65000
10    Kevin   45        Austin   90000
12  Michael   38      Columbus   75000
13     Nina   33     Charlotte   68000
14   Oliver   36       Seattle   80000

In [50]:
df.loc[df['age'] >= 30]

       name  age          city  salary
1       Bob   30   Los Angeles   60000
2   Charlie   35       Chicago   70000
5     Frank   40  Philadelphia   85000
6     Grace   32   San Antonio   62000
9      Jack   31      San Jose   65000
10    Kevin   45        Austin   90000
12  Michael   38      Columbus   75000
13     Nina   33     Charlotte   68000
14   Oliver   36       Seattle   80000

In [59]:
df[(df['age'] >= 30) | (df['salary'] > 60000)]

       name  age          city  salary
1       Bob   30   Los Angeles   60000
2   Charlie   35       Chicago   70000
5     Frank   40  Philadelphia   85000
6     Grace   32   San Antonio   62000
9      Jack   31      San Jose   65000
10    Kevin   45        Austin   90000
12  Michael   38      Columbus   75000
13     Nina   33     Charlotte   68000
14   Oliver   36       Seattle   80000

In [61]:
df[(df['age'] >= 30) | (df['salary'] > 60000)][['name','age','salary']]

       name  age  salary
1       Bob   30   60000
2   Charlie   35   70000
5     Frank   40   85000
6     Grace   32   62000
9      Jack   31   65000
10    Kevin   45   90000
12  Michael   38   75000
13     Nina   33   68000
14   Oliver   36   80000

In [55]:
df.loc[(df['age'] >= 30) & (df['salary'] >= 60000), ['name','age','salary']]

       name  age  salary
1       Bob   30   60000
2   Charlie   35   70000
5     Frank   40   85000
6     Grace   32   62000
9      Jack   31   65000
10    Kevin   45   90000
12  Michael   38   75000
13     Nina   33   68000
14   Oliver   36   80000